name: bbk_ocr_uat
description: BBK OCR UAT
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # OCR (على الجهاز)
  google_mlkit_text_recognition: ^0.13.0

  # اختيار صورة/كاميرا
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
